version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
